---
theme: jordandwhalen
collections:
  projects:
    output: true
    permalink: /:collection/:name
include: ["_pages"]
permalink: /:title/
cloudinary_url: "https://res.cloudinary.com/jordandwhalen/"
---
