---
hide_body: false
is_partial: false
fields:
- type: text
  name: client
  label: Client
  description: Name of the client that the work was done for.
  config:
    required: false
  default: Client Name
- type: text
  name: project_title
  label: Project Title
  description: Name for the work that was done on the project.
- type: image_gallery
  name: project_image
  label: Project Image
  description: An image that will be used in hero, and card variations of the project.
- type: textarea
  name: project_description
  label: Project Description
  description: Short description of the work that was done.
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: field_group
- type: textarea
  name: project_details
  label: Project Details
  description: Full details of the project.
  config:
    wysiwyg: true
    schema:
      format: markdown
